docs: @farcaster/js
farcasterxyz/hubble pull request #590
Opened 2023-02-18 08:52 UTC by vinliao

## Motivation

Add docs to @farcaster/js package.

## Change Summary

Initial file and table structure for the docs. Not done yet, just wanted to solicit feedback for these changes before we continue further.

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [x] The title of this PR adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [x] The PR has been tagged with the appropriate change type label(s) (i.e. documentation, feature, bugfix, or chore)
- [ ] Changes to the protocol specification have been merged

## Additional Context

"Description" column is generated by GPT, so it may be weird at times. Just wanted to get the file and table structure right for now. Please give feedback if you have any!

2023-02-22 20:25 UTC, varunsrin commented
@deodad would be worth a review from you

2023-02-22 23:19 UTC, deodad commented
@vinliao thanks for the PR!

In #555 you mention of using an automated tool to build these docs but I don't see anything here. Are these docs generated manually or automatically?

I'd like to see something like:
- annotations are made following [TSDoc](https://tsdoc.org/) directly in code files (easier to maintain + shows up in hover information)
- markdown is generated using TypeDoc or a similar tool
- package README has docs table of contents + section about how the docs are generated (see #562)

2023-02-23 00:27 UTC, vinliao commented
I actually generated a bunch of markdown files with TypeDoc, but it's not pretty: https://github.com/vinliao/fcjs-docs-md. The markdowns in the PR is mostly manual. Re TSDoc: #555 seems to only be about markdown, that's why this PR is only markdown. But do let me know if TSDoc is necessary and I'll add it.

2023-02-23 01:49 UTC, deodad commented
If we can make annotations using TSDoc and generate markdown with TypeDoc I think it's a big gain in terms of usability and maintenance costs, so I'm in favor of going with your original approach.

Taking a look at one of the TypeDoc outputted [markdown files](https://github.com/vinliao/fcjs-docs-md/blob/master/classes/Eip712Signer.md), it doesn't look bad imo, just sparse since there aren't many comments in that file. Wondering more specifically what you didn't like when you said it's not pretty? Thinking if we took the examples and descriptions you added to [Eip712Signer.md](https://github.com/farcasterxyz/hubble/blob/b933e0c59b4d39f98b65200c6db7e3b67c95278c/packages/js/docs/Eip712Signer.md), added them as [TSDoc annotations](https://tsdoc.org/) to `eip712Signer.ts`, and re-generated it'd be pretty darn nice.

2023-02-23 04:18 UTC, vinliao commented
With TypeDoc: https://github.com/vinliao/hubble/blob/md-docs/packages/js/docs/classes/js_src.Eip712Signer.md. I've configured `docs` script on the root `package.json`, so now it's the matter of adding docs to the TS files (still missing a lot!).

2023-02-23 06:23 UTC, varunsrin commented
I like the direction in the Eip712Signer file [here](https://github.com/vinliao/hubble/blob/md-docs/packages/js/docs/classes/Eip712Signer.md). I think with enough annotations the auto-generated format looks decent. 

@vinliao one suggestion is to do break this up into smaller PR's to parallelize the work. the initial PR can just set the guidelines for how to comment and generate documentation, and do that for a single file. follow on pr's can document each file, and they can be done slowly and by different people if necessary.

2023-02-23 07:44 UTC, vinliao commented
The initial structure is actually done I think, the rest is about adding TSDoc comments and running `yarn docs` to generate the docs. Is the current branch good enough to be merged? I think I can write a small contribution guide in `contributing.md` or something inside `packages/js`. Thoughts? Anything I'm missing?

2023-02-23 15:01 UTC, varunsrin requested changes
Generally, looks good, I'd make a few suggestions here: 

1. Rebase on the latest and regenerate docs, since some of the methods have been recently changed 

2. Exclude files that only have boilerplate documentation like Client, modules, types and utils so that we remember to add useful documentation and regenerate later. 

3. Open up a list of files that are excluded and must be documented in the ticket, so that someone can pick up the follow ups.

2023-02-23 15:05 UTC, varunsrin requested changes

2023-02-23 15:05 UTC, varunsrin commented on CONTRIBUTING.md
> +- To generate docs for `packages/*`, run `yarn docs` in the root of the monorepo. To see how the TSDoc comment is formatted, see [signMessageHash() in ed25519Signer.ts](packages/utils/src/signers/ed2
this isn't strictly true, since the protobufs package has a more involved generation process that is documented in its README.md.

2023-02-23 16:03 UTC, deodad submitted a review, later dismissed
A few small changes. 

Agree w/ @varunsrin suggestion to that excluding docs from certain parts would be nice, but technically none of it is wrong so I don't think this needs to block.

One more thought: what do you think of using setting up `typedoc` in `packages/js` instead of the root level? A modular approach may make it easier to setup each package to generate its own `docs` folder (for instance packages/protobufs generates its documentation using protoc-gen-doc).

2023-02-24 00:36 UTC, vinliao commented on CONTRIBUTING.md
> +- To generate docs for `packages/*`, run `yarn docs` in the root of the monorepo. To see how the TSDoc comment is formatted, see [signMessageHash() in ed25519Signer.ts](packages/utils/src/signers/ed2
Ah, yep, forget about the protobufs, change `packages/*` to `packages/js` and it should be good to go?

2023-02-24 00:38 UTC, vinliao commented
@deodad The TypeDoc was initially inside `packages/js`, but since it depends on utils (which means it has to go `../utils`, many things were broken. Are there downside to putting the docs script on the root compared to `packages/js`?

2023-02-24 00:42 UTC, varunsrin commented on CONTRIBUTING.md
> +- To generate docs for `packages/*`, run `yarn docs` in the root of the monorepo. To see how the TSDoc comment is formatted, see [signMessageHash() in ed25519Signer.ts](packages/utils/src/signers/ed2
yeah

2023-02-24 00:42 UTC, varunsrin commented
> @deodad The TypeDoc was initially inside `packages/js`, but since it depends on utils (which means it has to go `../utils`, many things were broken. Are there downside to putting the docs script on the root compared to `packages/js`?

fine for this release i think

2023-02-24 00:52 UTC, vinliao commented on packages/js/docs/README.md
> +TODO: explain what protobufs are, and what this package does under the hood
Seems useful to give a one (or two) sentence explanation about how Hubble works, so JS devs can understand what they're working with. Maybe point to the protocol docs instead?

2023-02-24 00:59 UTC, vinliao commented on packages/js/docs/classes/Ed25519Signer.md
> +[js/src/signers.ts:128](https://github.com/vinliao/hubble/blob/7629cfa/packages/js/src/signers.ts#L128)
Made the change. Is there a way to also disable "inherited from" text with another TypeDoc option? (Not critical, but I think it's quite verbose).

![image](https://user-images.githubusercontent.com/34117807/221065840-b809fbbc-ed41-4caf-868e-b64145281cf1.png)

2023-02-24 02:44 UTC, vinliao commented
Should there be docs TODOs on utils (https://github.com/vinliao/hubble/blob/md-docs/packages/js/docs/modules/utils.md)? All seems to be internal functions that JS devs don't have to touch.

2023-02-24 03:29 UTC, deodad commented
> Should there be docs TODOs on utils (https://github.com/vinliao/hubble/blob/md-docs/packages/js/docs/modules/utils.md)? All seems to be internal functions that JS devs don't have to touch.

I think it's fine to leave these out for now

2023-02-24 03:32 UTC, deodad commented on packages/js/docs/README.md
> +TODO: explain what protobufs are, and what this package does under the hood
That seems resonable!

2023-02-24 03:38 UTC, deodad commented on packages/js/docs/README.md
> +@farcaster/js / [Exports](modules.md)
I see that this same file exists at `packages/js/docs/README.md` and `packages/js/README.md`, is this intentional (e.g. file copied over when typedoc is run) or should we pick one?

2023-02-24 03:50 UTC, vinliao commented on packages/js/docs/README.md
> +@farcaster/js / [Exports](modules.md)
`js/docs/README.md` is generated from `/js/README.md`. It's kind of redundant, but not sure how to turn that off. `js/README.md` is what users will see, and the links inside it will point to the client docs, signer docs, etc.

2023-02-24 05:14 UTC, varunsrin approved these changes

2023-02-24 05:15 UTC, merged