fix: getCastsByFid should return items in reverse chronological order
farcasterxyz/hubble pull request #634
Opened 2023-03-10 08:09 UTC by bstchow

## Motivation
Fixes https://github.com/farcasterxyz/hubble/issues/611

## Change Summary
Modifies CastStore#getCastAddsByFid to fetch all messages for a given FID rather than only CastAdds from the DB.
Fetching all messages utilizes thash so casts are retrieved in chronological order.

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [x] The title of this PR adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [x] The PR has been tagged with the appropriate change type label(s) (i.e. documentation, feature, bugfix, or chore)
- [x] Changes to the protocol specification have been merged

## Additional Context
Not sure that I fully understood approach described in https://github.com/farcasterxyz/hubble/issues/611
If I understand correctly, it seems like this is a bandaid, and long term it might make sense to have a parallel index RocksDB table stored with thash keys?

2023-03-12 00:11 UTC, pfletcherhill requested changes

2023-03-12 00:11 UTC, pfletcherhill commented on apps/hubble/src/storage/stores/castStore.ts
> +    return (await getAllMessagesByFid(this._db, fid))
This should still use a rocksdb iterator, but instead of using the cast adds prefix, it should use the cast messages prefix (i.e. `Buffer.concat([makeUserKey(fid), Buffer.from([UserPostfix.CastMessage])])`. Also, I think it's okay to return chronological order rather than reversed chronological.

2023-03-13 06:24 UTC, bstchow commented on apps/hubble/src/storage/stores/castStore.ts
> +    return (await getAllMessagesByFid(this._db, fid))
Gotcha - that makes sense. Let me know if the latest changes have addressed this.

2023-03-13 06:25 UTC, bstchow commented on apps/hubble/src/storage/stores/castStore.ts
> +      const msg = protobufs.Message.decode(value);
Seemed like the most declarative way to get the MessageType, also not sure what offset I should expect type to be at

2023-03-15 05:16 UTC, pfletcherhill commented
Closing this PR since we've integrated the commits into a separate PR that involves ordering and pagination: https://github.com/farcasterxyz/hubble/pull/610/

2023-03-15 05:16 UTC, closed without merging