docs(hub-nodejs): add docs for utils.md
farcasterxyz/hubble pull request #736
Opened 2023-03-23 13:37 UTC by vinliao

## Motivation

Fixes #735. See: https://github.com/vinliao/hubble/blob/nodejs-docs/packages/hub-nodejs/docs/Utils.md

## Change Summary

Add examples and the tables for each function in `utils.md`

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [x] PR title adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [ ] PR has a [changeset](../CONTRIBUTING.md#35-adding-changesets)
- [x] PR has been tagged with a change label(s) (i.e. documentation, feature, bugfix, or chore)
- [x] PR does not require changes to the [protocol](https://github.com/farcasterxyz/protocol)

## Additional Context

If this is a relatively large or complex change, provide more details here that will help reviewers

2023-03-23 21:47 UTC, varunsrin requested changes
thanks so much for this @vinliao!

left a few comments, but looks great otherwise

2023-03-23 21:47 UTC, varunsrin commented on packages/hub-nodejs/docs/Utils.md
> +const data = wrappedData._unsafeUnwrap();
only use _unsafeUnwrap() in examples or tests where you control the inputs. in this case, since the input is coming from a method we should encourage users to handle the failure case with something like: 

````
const eventResult = await client.getIdRegistryEvent({ fid: 1 });

if (eventResult.isErr()) {
    console.log(eventResult.error);
    return;
}

const event = eventResult.value;
```

2023-03-23 21:47 UTC, varunsrin commented on packages/hub-nodejs/docs/Utils.md
> +console.log('Block hash (hexadecimal):', blockHashHex); // 0x318c1013788674...
doesn't bytesToHexString return a result that needs to be unwrapped?

2023-03-23 21:47 UTC, varunsrin commented on packages/hub-nodejs/docs/Utils.md
> +const byteArray = hexStringToBytes(hexString)._unsafeUnwrap();
would add a comment at the end of the line with `// Safety: hexString is known and can't error`

2023-03-23 21:47 UTC, varunsrin commented on packages/hub-nodejs/docs/Utils.md
> +const utfEncodedStr = bytesToUtf8String(byteArray)._unsafeUnwrap();
same note about the // Safety: comment

2023-03-23 21:47 UTC, varunsrin commented on packages/hub-nodejs/docs/Utils.md
> +console.log(timestamp._unsafeUnwrap()); // 70117755
nit: i would do the unwrap on the line above to make it easier for people to grok

2023-03-23 21:47 UTC, varunsrin commented on packages/hub-nodejs/docs/Utils.md
> +| Name   | Type   | Description                               |
you can just delete the entire parameters section

2023-03-23 21:47 UTC, varunsrin commented on packages/hub-nodejs/docs/Utils.md
> +const wrappedData = await client.getCastsByFid({ fid: 1 });
can we just hard code an example input instead of having the user fetch one from the hub? it simplifies this example a lot

2023-03-24 01:13 UTC, vinliao commented
Should be good now, @varunsrin.

2023-03-24 02:15 UTC, varunsrin reviewed
two very minor nits

2023-03-24 02:15 UTC, varunsrin commented on packages/hub-nodejs/docs/Utils.md
> +const utfEncodedStr = bytesToUtf8String(byteArray)._unsafeUnwrap();
this should say `byteArray` is known :)

2023-03-24 02:15 UTC, varunsrin commented on packages/hub-nodejs/docs/Utils.md
> +// Safety: hexString is known and can't error
this should say byteArray is known

2023-03-24 02:43 UTC, vinliao commented on packages/hub-nodejs/docs/Utils.md
> +// Safety: hexString is known and can't error
Whoops, missed that.

2023-03-24 05:13 UTC, varunsrin approved these changes

2023-03-24 05:13 UTC, merged